### ISSUE TITLE
Disable csgo knives as a traitor weapon in TTT

### ISSUE THREAD

**Issue by Lance0001** [xDShot/csgo_knives_sweps#1]
What would be the best method to disable CSGO knives as a traitor weapon in TTT?

**Comment by xDShot** [comment]
For now, in each lua file switch SWEP.CanBuy to nil:
```lua
SWEP.CanBuy = nil
```

This makes so the traitors won't be able to buy it from buymenu. You'd need to figure it out how to deliver them to players (ex. Pointshop) as they are usually accessable only through buymenu and not randomspawnable.

**Comment by xDShot** [comment]
Please see this:
https://github.com/xDShot/csgo_knives_sweps/issues/2
