### ISSUE TITLE
Knife skin won't appear on Arizard Deathrun gamemode

### ISSUE THREAD

**Issue by Oyplap** [xDShot/csgo_knives_sweps#11]
I use https://github.com/Arizard/deathrun and i also use Pointshop 2 but the skin of the knives won't appear.

On my sandbox server it works:
![Aantekening 2020-08-07 172605](https://user-images.githubusercontent.com/45702131/89661630-36f5d100-d8d3-11ea-971e-779ef407e700.png)

But not on my Deathrun server:
![Aantekening 2020-08-07 172756](https://user-images.githubusercontent.com/45702131/89661773-64db1580-d8d3-11ea-9f6f-9f5937a04ca5.png)
When i drop it, it does appear:
![Aantekening 2020-08-07 172753](https://user-images.githubusercontent.com/45702131/89661799-6d335080-d8d3-11ea-8252-89d2612317ff.png)

What should i do?

**Comment by xDShot** [comment]
See #5
