### ISSUE TITLE
All of the Gamma Knives textures do not work

### ISSUE THREAD

**Issue by Morggs27** [xDShot/csgo_knives_sweps#3]
Basically all the knives work perfectly for me other than the gamma ones, the knives textures (skins) show the pink and black checkerboard, therefore the textures do not work for all of them as i have tried every gamma knife

**Comment by xDShot** [comment]
Are you using workshop version or this?

**Comment by Morggs27** [comment]
I have it on the workshop, but also downloaded from this as well, just a few knives are bugged.

**Comment by xDShot** [comment]
Well, there is a separate gamma skin pack in workshop, it should be downloaded as well to get it working

**Comment by xDShot** [comment]
@Morggs27 does it work for you?
