### ISSUE TITLE
Knife Damage won't change

### ISSUE THREAD

**Issue by colbyhenley1** [xDShot/csgo_knives_sweps#4]
Hi there, I've tried to change the damage by using the your commands in my console and I've tried putting the changes in my server config but nothing works. When I do the commands in console it tells me that i'm trying unknown commands. I'm not sure what to do at this point.

**Comment by xDShot** [comment]
These are the serverside console commands. Try setting them in either server's console screen or through RCon.

**Comment by xDShot** [comment]
@colbyhenley1 does it work for you?
