### ISSUE TITLE
SWEP's knives textures/skins don't load

### ISSUE THREAD

**Issue by Fanatrix10** [xDShot/csgo_knives_sweps#8]
So, I have a Garry's Mod Deathrun server, with Pointshop 2, and I downloaded the CS GO Knives SWEPs addon, I put it in the addon folder, and then I restarted my server.
After joining the server, I saw the knives, but when I equipped them, they were normal vanilla skins, in Pointshop 2 the textures / skins were there, and when I dropped them on the floor too, not only I had this bug, also the people who played on my server.
I hope someone can help me!
Thank you.
https://imgur.com/a/cmR8gWM ( Gut Knife | Gamma Doppler )

**Comment by xDShot** [comment]
>Deathrun server

Which one exactly?

**Comment by ceifa** [comment]
> Which one exactly?

Deathrun neue by Arizard, i guess
The solution is on issue #5
